name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: lint-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm ci
    - run: npm run lint
    - run: npm test
